name: Generate SBOM

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # Optional: Allow manual triggering

jobs:
  generate_sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 

      - name: Install Syft
        run: pip install syft

      - name: Generate SBOM (CycloneDX)
        run: syft packages dir:. -o cyclonedx-json sbom.cdx.json 

      - name: Generate SBOM (SPDX)
        run: syft packages dir:. -o spdx-json > sbom.spdx.json 

      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sboms
          path: |
            sbom.cdx.json
            sbom.spdx.json 
